# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('a_paterno', models.CharField(max_length=150)),
                ('a_materno', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=150)),
                ('f_nacimiento', models.DateField(null=True)),
                ('sexo', models.CharField(max_length=150)),
                ('e_civil', models.CharField(max_length=150)),
                ('ocupacion', models.CharField(max_length=150)),
                ('religion', models.CharField(max_length=150)),
                ('tipo_sanguinio', models.CharField(max_length=150)),
                ('domicilio', models.CharField(max_length=150)),
                ('colonia', models.CharField(max_length=150)),
                ('cp', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=254)),
                ('estado', models.CharField(max_length=150)),
                ('municipio', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='medics',
        ),
    ]
