# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180318_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('agendar', models.BooleanField(default=False)),
            ],
        ),
    ]
