# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180320_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='descripcion',
            field=models.TextField(default=None),
        ),
    ]
