# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180320_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='alergias',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='andrologicos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='ginecologos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='heredados',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='nopatologicos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='observaciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patologicos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='perinatales',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='quirurgicos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
