# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180320_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(max_length=150)),
                ('temperatura', models.CharField(max_length=150)),
                ('peso', models.CharField(max_length=150)),
                ('estatura', models.CharField(max_length=150)),
                ('presion_arterial', models.CharField(max_length=150)),
                ('talla', models.CharField(max_length=150)),
                ('imc', models.CharField(max_length=150)),
                ('cabeza', models.TextField()),
                ('torax', models.TextField()),
                ('abdomen', models.TextField()),
                ('genitales', models.TextField()),
                ('piel', models.TextField()),
                ('diagnostico', models.TextField()),
                ('pronostico', models.TextField()),
                ('terapeuticas', models.TextField()),
                ('f_consulta', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patients')),
            ],
        ),
    ]
