# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='receta_procedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Procedure')),
            ],
        ),
    ]
