# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180325_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='f_end',
        ),
    ]
