# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_diary_f_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=600)),
                ('correo', models.CharField(max_length=600)),
                ('telefono', models.CharField(max_length=600)),
                ('facebook', models.CharField(max_length=600)),
                ('twitter', models.CharField(max_length=600)),
                ('youtube', models.CharField(max_length=600)),
                ('lema', models.CharField(max_length=600)),
            ],
        ),
    ]
