# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_properties_r_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='heredados',
        ),
    ]
