# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_patients_heredados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='cabeza',
            new_name='exp_fisica',
        ),
        migrations.AddField(
            model_name='receta',
            name='extremidades',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='p_actual',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
