# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180328_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='indicaciones',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
