# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_receta_indicaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='indicaciones',
        ),
    ]
