# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_receta_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='cintura',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
