# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180515_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='file5',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='file6',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='file7',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='file8',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='file9',
        ),
    ]
