# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20180515_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='file1',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='file2',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='file3',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='file4',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='file5',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='file6',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='file7',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='file8',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='file9',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='file0',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
