# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_procedure_monedero'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='monedero',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
