# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_patients_monedero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='monedero',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
