# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20180516_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='id_monedero',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
