# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0035_receta_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='medic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
