# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_patients_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
